### PR TITLE
Make extension v12 compatible and support DashboardWidgets

### PR DESCRIPTION
**Pull request by ohartwig**
Bug fix:
- Allow all submodules
- CE Types allow List

Feature:
- Support for DashboardWidgets

### CODE REVIEW

**Comment by bmack** [comment]
Thanks for your patch. As we'd like to keep v11 compatibility as long as possible, can we split up the PR in "add support for Dashboard Widgets" and then v12 compatibility separately? We could then use a `(new Typo3Version())->getMajorVersion() > 11` switch to support both versions.

**Comment by ohartwig** [comment]
Sure, here is the PR for the Dashboard Widgets https://github.com/b13/permission-sets/pull/4

**Comment by ohartwig** [comment]
Thank you for your feedback. Here is the version with v11 and v12 support.

**Review by bmack — APPROVED** [review]
Thanks for the quick update, really great!

**Review by bmack — APPROVED** [review]

**Pull request merged**
